### ISSUE TITLE
可视化问题

### ISSUE THREAD

**Issue by yyqgood** [Owen-Liuyuxuan/visualDet3D_ros#1]
首先，感谢你的贡献：
我修改了适配自己的配置，如下：

![launch](https://user-images.githubusercontent.com/34564480/134610578-5feddfd8-061f-4bea-bc32-b3169a8880fe.png)

使用：roslaunch yolo3d yolo3d.launch 命令启动，启动信息如下：

![screenshot](https://user-images.githubusercontent.com/34564480/134610649-107eb382-2c20-4c30-9bb7-a71ed06793b6.png)

一直停在这边，没有显示界面？请问是我遗漏了什么吗？
期待你的回复，谢谢！

**Comment by Owen-Liuyuxuan** [comment]
界面不是由本repo提供的，这个package是一个yolo3d的inference code。可视化的内容是使用了ROS Rviz，而本repo没有也暂无计划包含可视化的功能内容。

内部的kitti visualizer在未来可能会开源，但是未定。

你只需要另外写一个ros node脚本从 KITTI 或者其他数据源中读取并发布图片序列，同时发布 camera_info. 本repo的code负责基于图片流发布object marker. 再打开Rviz就能完成可视化.

**Comment by Owen-Liuyuxuan** [comment]
从你的配置观察， 注意两个camera_topic  camera_param 两个参数实际上对应的是两个 ROS topic

**Comment by yyqgood** [comment]
多谢你的回复，我将尝试它。
